# Generated by Django 3.1.7 on 2021-09-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210711_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=150)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
