# Generated by Django 3.1.7 on 2021-09-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210916_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_status',
            field=models.BooleanField(default=False),
        ),
    ]
